# Generated by Django 4.2.5 on 2023-10-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stripe_checkout_id',
            field=models.CharField(default='def', max_length=500),
            preserve_default=False,
        ),
    ]
