# Generated by Django 4.2.5 on 2023-10-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_stripe_checkout_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFeePaidStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=30)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
