# Generated by Django 4.2.5 on 2023-10-03 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_schoolfeepaidstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfeepaidstudent',
            name='id',
        ),
        migrations.AddField(
            model_name='schoolfeepaidstudent',
            name='std_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
