# Generated by Django 4.2.5 on 2023-10-17 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_school_studentcontact_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontact',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentcontact',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4,}/\\d{5,}[A-Za-z]{2}$')], verbose_name='username'),
        ),
    ]
