# Generated by Django 4.2.5 on 2023-10-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_blood_group_user_dob_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcontact',
            name='parent_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentcontact',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
