# Generated by Django 4.2.5 on 2023-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_hall_picture_hall_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='gender',
            field=models.CharField(choices=[('boys', 'boys'), ('girls', 'girls')], default='boys', max_length=8),
        ),
        migrations.AlterField(
            model_name='hall',
            name='picture',
            field=models.ImageField(default='img/bld.jpeg', upload_to='img/'),
        ),
    ]
