# Generated by Django 4.2.5 on 2023-09-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_hall_gender_alter_hall_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
